version: '3.5'

name: wordpress-${DOMAIN}

services:
  wordpress:
    container_name: wordpress-${DOMAIN}
    build: .
    volumes:
      - /var/www/${DOMAIN}/wp-content:/var/www/wp-content
    environment:
      WORDPRESS_SITE_URL: https://${DOMAIN}.${DOMAIN_TLD}
      FS_METHOD: direct
    networks:
      - caddy
    labels:
      caddy_0: ${DOMAIN}.${DOMAIN_TLD}
      caddy_0.reverse_proxy: "{{upstreams 80}}"
      caddy_1: www.${DOMAIN}.${DOMAIN_TLD} ${DOMAIN_ALIASES}
      caddy_1.redir: https://${DOMAIN}.${DOMAIN_TLD}

networks:
  caddy:
    external: true
